apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
        app: nginx
        tier: frontend                # Upto here this is replica set definition 
  template:                             # From here POD definition starts 
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx:{{ .Values.imageversion}}
        image: nginx
        imagePullPolicy: Always